### ISSUE TITLE
[✨ feature] I18n initiative

### ISSUE THREAD

**Issue by AugustinMauroy** [Fredkiss3/gh-next#65]
## I18n app

If we want to provide i18Nn we will need somethings

## TODO:

* [ ] Setup infra:
  * Use `lang` nextjs params
  * Use [react-intl](https://formatjs.io/docs/react-intl/) pour les formatted message
  * Fetch message for the local context
* [ ] add all key for all component
* [ ] document how to translate

- [ ] Are you willing to make a PR for this ? @AugustinMauroy

**Comment by Fredkiss3** [comment]
I learned about [next-international](https://github.com/QuiiBz/next-international) and it seemed very rich in features, did you look or hear about it ?

**Comment by AugustinMauroy** [comment]
I nearly same as `react-intl` but react intl have more component such as date

**Comment by AugustinMauroy** [comment]
Here an example of how it's will look like:
https://github.com/AugustinMauroy/nodejs.org-monorepo-poc/tree/main/apps/nodejs-website

**Comment by Fredkiss3** [comment]
> I nearly same as `react-intl` but react intl have more component such as date

Oh ! this is pretty cool then ! I can't wait to see how it will look  👀
